project-master/config/routes.rb
Rails.application.routes.draw do

  resources :groupmembers
  resources :course_modules
  resources :projects
  resources :preferences
  resources :pairings
  resources :groups
  resources :lecturers
  resources :students
  devise_for :users
  resources :course_modules
  resources :projects
  resources :preferences
  resources :pairings
  resources :groups
  resources :students
  resources :lecturers do
    collection {post :import}
  end
  resources :admins
  resources :users

  mount EpiCas::Engine, at: "/"
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all
  get "/suspend", to: "users#suspend", :as => 'suspend'
  get '/createPreference' => 'preferences_controller#createPreference', :as => 'createPreference'

  get :ie_warning, to: 'errors#ie_warning'
  get 'lecturer_dashboard', to: 'lecturers#dashboard'
  get 'student_dashboard', to: 'students#dashboard'
  get 'select_groupset', to: 'lecturers#groupsetSelect'
  get 'lecturer_organise', to: 'lecturers#organiseGroups'
  get 'lecturer_organise_teams', to: 'lecturers#organiseTeams'
  get 'lecturer_organise_students', to: 'lecturers#organiseStudents'
  get 'lecturer_grouping', to: 'lecturers#grouping'
  get 'group_details', to: 'lecturers#group_details'
  get 'lecturer_form', to: 'groups#new'
  get 'preferences_form', to: 'preferences#_form'
  get 'profile', to: 'users#profile'
  get 'upload', to: 'lecturers#upload_csv'
  get 'form', to: 'students#form'
  get 'emails', to: 'lecturers#emails'
  get 'lecturers_main_page', to: 'lecturers#index'
  get 'students_main_page', to: 'students#index'
  get 'my_group', to: 'students#mygroup'
  get 'admin_user_info', to: 'admins#user_info'
  get 'run_algo', to: 'lecturers#run_algo'
  post 'lecturer/runAlgo', to: 'lecturers#runAlgo'
  post 'admin/importlecturers' , to: 'admins#import_lecturers'
  post 'lecturer/importstudents' , to: 'lecturers#import_students'
  post 'lecturer/setCurrentGroupSet', to: 'lecturers#setCurrentGroupSet'
  post 'lecturer/setCurrentGroupSetOrganise', to: 'lecturers#setCurrentGroupSetOrganise'
  post 'lecturer/setCurrentGroupSetAssigned', to: 'lecturers#setCurrentGroupSetAssigned'
  post 'lecturer/setCurrentModule', to: 'lecturers#setCurrentModule'
  post 'student/setCurrentModule', to: 'students#setCurrentModule'
  post 'lecturer/setTeam', to: 'lecturers#setTeam'
  post 'lecturer/removeStudent', to: 'lecturers#removeStudent'
  post 'lecturer/addStudent', to: 'lecturers#addStudent'
  post 'admin/suspenduser', to: 'admins#suspend_user'
  post 'admin/promoteadmin', to: 'admins#promote_admin'
  post 'admin/unsuspenduser', to: 'admins#unsuspend_user'
  post 'admin/demoteadmin', to: 'admins#demote_admin'
  post 'student/getgroup', to: 'students#get_group'
  get 'lecturer/exportGroupMembers', to: 'lecturers#exportGroupMembers'

  # admins routes
  get 'admins_main_page', to: 'admins#index'
  get 'admin_csv', to: 'admins#upload_csv'
  get 'user_info', to: 'admins#user_info'
  
  get 'classlistexport', to: 'admins#classlist_csv'

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # Commented out temporarily to be used to test admin pages
  # TO BE REMOVED BEFORE FINAL SUBMISSION
   #root to: "admins#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project-master/app/models/lecturer.rb
# == Schema Information
#
# Table name: lecturers
#
#  id              :bigint           not null, primary key
#  currentGroupSet :string
#  currentTeam     :string
#  email           :string
#  modules         :string
#  senior          :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

require 'csv'

class Lecturer < ApplicationRecord
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
        if Student.find_by(username: row.field('Student Username')) != nil
          student = Student.find_by(username: row.field('Student Username'))
          module_list = student.modules.split(",")
          if module_list.include?(row.field('Module Code'))
            nil
          else 
            module_list.push(row.field('Module Code'))
          end
          student.update(modules: module_list.join(','))
        else
          middlename = row.field('Middle Names')
          if middlename == nil
            middlename = ""
          end
          if (User.find_by(username: row.field('Student Username'))) == nil
            puts ('HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII')
            user = User.new(username: row.field('Student Username'))
            user.get_info_from_ldap
            user.save
          end
          Student.create!(forename:row.field('Forename'), middlename:middlename, surname:row.field('Surname'), username:row.field('Student Username').downcase, feeStatus:row.field('Fee Status'), programme:row.field('Programme'), gender:'', modules:row.field('Module Code'))
        end
    end
  end



  
end

project-master/app/controllers/lecturers_controller.rb
require 'csv'

class LecturersController < ApplicationController
  before_action :set_lecturer, only: [:show, :edit, :update, :destroy]
  helper_method :get_modules
  helper_method :get_groupSet
  helper_method :get_teams
  helper_method :get_students
  helper_method :getTeamName
  helper_method :getMembers
  helper_method :getAllTeams
  helper_method :getUATeam
  helper_method :getGroupSetAlgorithm

  #authorize_resource
  # GET /lecturers
  def index
    @lecturers = Lecturer.all

    respond_to do |format|
      format.html
      format.csv do
          response.headers['Content-Type'] = 'text/csv'
          response.headers['Content-Disposition'] = 'attachment; filename=invoice.csv'    
          send_data Lecturer.to_csv(current_user.email)
      end
    end
  end

  # GET /lecturers/dashboard
  def dashboard
  end

  # GET /lecturers/organise
  def organise
    @students = Student.all
  end

  # GET /lecturers/grouping
  def grouping
  end

  # GET /lecturers/group_details
  def group_details
  end
  
  # GET /lecturers/upload_csv
  def upload
  end

  # GET /lecturers/1
  def show
  end

  # GET /lecturers/new
  def new
    @lecturer = Lecturer.new
  end

  # GET /lecturers/1/edit
  def edit
  end

  def with
  end

  # POST /lecturers
  def create
    @lecturer = Lecturer.new(lecturer_params)
     if @lecturer.save
        #render "post_created"
        redirect_to lecturer_dashboard_path, notice: "Post was successfully sent."
      end
  end

  def exportGroupMembers
      Lecturer.exportGroupMembers(current_user.email)
      redirect_to lecturer_grouping_path notice: 'Downloading GroupMembers'
  end

  def import_students
    if !(params.to_s.include?("filename")) # checks if a file was submitted
      flash[:notice] = "Please attach a CSV file"
      redirect_to lecturer_csv_path
    else
      filetype = params[:search][:file]
      if ((filetype.to_path)).include?("csv")
        Lecturer.import(params[:search][:file])
        flash[:notice] = "File uploaded successfully"
        redirect_to lecturer_dashboard_path
      else
        flash[:notice] = "Must be CSV"
        redirect_to lecturer_csv_path
      end
    end
  end

  def setCurrentModule
    if params[:search][:modules] == 'NONE'
      redirect_to lecturers_path, notice: 'You have not been initialised. Request an admin to initialise you in the system'
    else
      user = User.find_by(username: current_user.username)
      user.currentModule = params[:search][:modules]
      user.save
      redirect_to lecturer_dashboard_path
    end
  end

  def setCurrentGroupSetOrganise
    lecturer = Lecturer.find_by(email: current_user.email)
    lecturer.update(currentGroupSet: params[:search][:currentGroupSet])
    lecturer.update(currentTeam: "NONE")
    redirect_to lecturer_organise_path
  end

  def setCurrentGroupSetAssigned
    lecturer = Lecturer.find_by(email: current_user.email)
    lecturer.update(currentGroupSet: params[:search][:currentGroupSet])
    redirect_to lecturer_grouping_path
  end

  def runAlgo
    groupSet = params[:search][:currentGroupSet]
    Group.assignStudents(groupSet)
    for group in Group.where(groupSet:groupSet) do
      group.update(updated: true)
    end
    flash[:notice] = "Groups are now formed"
    redirect_to lecturer_dashboard_path
  end

  def setTeam
    lecturer = Lecturer.find_by(email: current_user.email)
    lecturer.update(currentTeam: params[:search][:teams])
    redirect_to lecturer_organise_path
  end
  
  #moveStudent
  def addStudent
    student_name = params[:search][:students]
    target = params[:search][:teams]
    team = Lecturer.find_by(email:current_user.email).currentTeam
    if target != team
      groupSet = Lecturer.find_by(email:current_user.email).currentGroupSet
      @old_group = Group.find_by(title: team, groupSet: groupSet)
      @new_group = Group.find_by(title: target, groupSet: groupSet)
      if team != "Unnassigned Team"
        team = team[6..-1]
      end
      if target != "Unnassigned Team"
        target = target[6..-1]
      end
      old_students = @old_group.groupMembers.split(',')
      new_students = @new_group.groupMembers.split(',')
      @student = Preference.find_by(groupSet:groupSet, full_name:student_name)
  
      @old_group.groupMembers = (old_students - [@student.username]).join(",")
      @new_group.groupMembers = (new_students + [@student.username]).join(",")
      @old_group.save
      @new_group.save

      @student.update(groupCode:target)
  
    end
    redirect_to lecturer_organise_path
  end


  def get_modules
    @lecturer = Lecturer.find_by(email: current_user.email)
    if @lecturer.nil?
      return [['NONE']]
    else
      module_list = @lecturer.modules.split(",")
      module_lists = []
      for module1 in module_list
        module_lists.push([module1])
      end
      return module_lists
    end
  end
  
  def get_groupSet
    @lecturer = Lecturer.find_by(email: current_user.email)
    currentModule = User.find_by(username: current_user.username).currentModule
    groups = Group.where(moduleCode: currentModule)
    groupSets = []
    for group in groups
      groupSets.push([group.groupSet])
    end
    groupSets = groupSets.uniq
    return groupSets
  end

  def getGroupSetAlgorithm
    @lecturer = Lecturer.find_by(email: current_user.email)
    currentModule = User.find_by(username: current_user.username).currentModule
    groups = Group.where(moduleCode: currentModule)
    groupSets = []
    currentDate = DateTime.now.to_date
    # +3600 accomodating for time zone
    currentTime = DateTime.now.to_time + 3600
    for group in groups
      deadline_date = group.deadline.to_date
      deadline_time = group.deadline.to_time
      if (((deadline_date < currentDate) | ((deadline_date == currentDate) & (deadline_time < currentTime)) & (group.updated != true)))
        groupSets.push([group.groupSet])
      end
    end
    groupSets = groupSets.uniq
    return groupSets
  end

  def get_teams
    groupSet = Lecturer.find_by(email: current_user.email).currentGroupSet
    groups = Group.where(groupSet: groupSet)
    groupNames = []
    for group in groups
      groupNames.push([group.title])
    end
    return groupNames
  end

  def get_students
    if Lecturer.find_by(email:current_user.email).currentTeam == "NONE"
      return [["VIEW A TEAM"]]
    else
      team = Lecturer.find_by(email:current_user.email).currentTeam
      groupSet = Lecturer.find_by(email:current_user.email).currentGroupSet
      students = Group.find_by(title: team, groupSet: groupSet).groupMembers.split(',')
      studentNames = []
      for student in students
        studentNames.push([Preference.find_by(username:student , groupSet: groupSet).full_name])
      end
      return studentNames
    end
  end

  def getMembers
    team = Lecturer.find_by(email:current_user.email).currentTeam
    if team != "NONE"
      groupSet = Lecturer.find_by(email:current_user.email).currentGroupSet
      students = Group.find_by(title: team, groupSet: groupSet).groupMembers.split(',')
      
      preferences = []
      for student in students
        preferences.push(Preference.find_by(username:student, groupSet: groupSet))
      end
    else
      preferences = []
    end
    puts preferences
    return preferences
  end

  def getUATeam
    groupSet = Lecturer.find_by(email:current_user.email).currentGroupSet
    return Preference.where(groupSet: groupSet, groupCode: 'Unnassigned Team')
  end

  def getAllTeams
    groupSet = Lecturer.find_by(email:current_user.email).currentGroupSet
    return Preference.where(groupSet: groupSet).where.not(groupCode: 'Unnassigned Team')
  end

  def getTeamName
    return Lecturer.find_by(email: current_user.email).currentTeam
  end

  # PATCH/PUT /lecturers/1
  def update
    if @lecturer.update(lecturer_params)
      redirect_to @lecturer, notice: 'Lecturer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lecturers/1
  def destroy
    @lecturer.destroy
    redirect_to lecturers_url, notice: 'Lecturer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecturer
      @lecturer = Lecturer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lecturer_params
      params.fetch(:lecturer, {})
    end
end

project-master/app/helpers/lecturers_helper.rb
module LecturersHelper
end

project-master/app/views/lecturers/dashboard.html.haml
%h1{:style => "margin: auto; background-color: RGB(110,213,244); width: 400px; border: 5px solid rgb(110,101,192); padding: 50px; text-align: center; "} My Services
 
%button.btn.btn-secondary{:style => "margin: 20px"}
 = link_to "Upload File", "upload", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Upload classlists in the form of CSV files.'

%button.btn.btn-secondary{:style => "margin: 20px"}
 = link_to "Organise / Assigned Groups", "select_groupset", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'View, manually adjust and release groups for a project. '

%button.btn.btn-secondary{:style => "margin: 20px"} 
 = link_to "Form Details", "lecturer_form", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px'

%button.btn.btn-secondary{:style => "margin: 20px"} 
 = link_to "Form Groups", "run_algo", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px'

%button.btn.btn-secondary{:style => "margin: 20px"} 
 = link_to "Send Emails", "emails", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Send email notifications to students.'
 
%button.btn.btn-secondary{:style => "margin: 20px"}
 = link_to "My Profile", "profile", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'View details of your profile.'

project-master/app/views/lecturers/emails.html.haml
%h4 Form Details

%br
= simple_form_for(Lecturer.new) do |f|

   = f.label :body, "Email Details"
   -#= f.text_area :body, size: "60x12"


   = f.button :submit, "Send Details", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size: 20px'

project-master/app/views/lecturers/form.html.haml
-# frozen_string_literal: true
= simple_form_for(@lecturers) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?



  .form-inputs

  .form-actions
    = f.button :submit

project-master/app/views/lecturers/grouping.html.haml
-content_for :title, 'View Groups'


.students 
 %table.table.table-bordered.table-secondary
  %thead 
   %tr
    %th UNNASSIGNED STUDENTS
  %tbody
   - if getUATeam.size >= 0
    -   getUATeam.each do |student|
     %tr
      %td= student.full_name

.students 
 %table.table.table-bordered.table-secondary
  %thead
   %tr
    %th Full Name
    %th Group
  %tbody
   - if getAllTeams.size >= 0
    -   getAllTeams.each do |student|
     %tr
      %td= student.full_name
      %td= student.groupCode

%button.btn.btn-secondary{:style => "margin: 20px"}
 = link_to "Export Group Members", "groupmembers.csv", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Once you are satisfied with the teams, click this button to export a CSV file containing the GROUPS and their respective MEMBERS to your device.'
%button.btn.btn-secondary{:style => "margin: 20px"}
 = link_to "Export Groups", "groups.csv", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Once you are satisfied with the teams, click this button to export a CSV file containing the GROUPS to your device.'

project-master/app/views/lecturers/groupsetSelect.html.haml
%h1 Select Groupset

%br
= simple_form_for :search, url: lecturer_setCurrentGroupSetOrganise_path do |f|
  = f.label :currentGroupSet, "Select Project:"
  = f.select :currentGroupSet, get_groupSet
 
  = f.button :submit, "Go to organise", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size:20px', :title=> 'Select a groupset from the dropdown box and then click this button to advance to the organise page.'
    
%br

= simple_form_for :search, url: lecturer_setCurrentGroupSetAssigned_path do |f|
  = f.label :currentGroupSet, "Select Project:"
  = f.select :currentGroupSet, get_groupSet
 
  = f.button :submit, "Go to assigned", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size:20px', :title=> 'Select a groupset from the dropdown box and then click this button to view the final teams for the respective groupset.'
    

project-master/app/views/lecturers/index.html.haml
%h1 Welcome

%br
= simple_form_for :search, url: lecturer_setCurrentModule_path do |f|
  = f.label :modules, "Module Code"
  = f.select :modules, get_modules
 
  = f.button :submit, "Go to module", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size:20px', :title=> 'Please select the module that you wish to access from the dropdown box. Then, click this button to proceed to dashboard page.'
    

project-master/app/views/lecturers/organiseGroups.html.haml
- content_for :title, "Organise Groups"
.organize-panel
  .view-button
    = simple_form_for :search, url: lecturer_setTeam_path do |f|
      = f.label :teams, "Team to view:"
      = f.select :teams, get_teams
    
      = f.button :submit, "View Team", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size:20px', :title=> 'Select a group from the dropdown box beside "Team to view:" and then click this button to view the existing members of a group. To move a student, use the "Move:" dropdown box to select an exisitng member of the group and the "To:" dropdown box to select the new group for the selected member. Then, click the "Move Student" button.'
    
  -# .remove-button
  -#   = simple_form_for :search, url: lecturer_removeStudent_path do |f|
  -#     = f.label :students, "Students"
  -#     = f.select :students, get_students
    
  -#     = f.button :submit, "Remove Student", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size:20px'
  
  .move-button
    = simple_form_for :search, url: lecturer_addStudent_path do |f|
      = f.label :students, "Move:"
      = f.select :students, get_students, inline_label: "Only works when 1st drop down is unasigned"

      %br
 
      = f.label :teams, "To:"
      = f.select :teams, get_teams
      = f.button :submit, "Move Student", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size:20px', :title=> 'Before clicking this button, please ensure that the right member from the group is selected from the dropdown box beside "Move:" and the intended group is selected from the dropdown box beside "To:".'

  .students
    = simple_form_for(Lecturer.new) do |f|
      %h7 Current team:
      = f.label :team, - getTeamName 
    %table.table.table-bordered.table-secondary
      %thead
        %tr
          %th Full Name
          %th Pair
          %th Unwanted partners
          %th Domicile
          %th Gender

        %tbody
          - if getMembers.size >= 0
            -  getMembers.each do |student|
              %tr 
                %td= student.full_name
                %td= student.partners
                %td= student.nonPartners 
                %td= student.feeStatus 
                %td= student.gender

project-master/app/views/lecturers/post_created.html.haml
%h1  Testing mailer

%p
  = ", find me in app/views/teacher_mailer/post_created.html.haml"

project-master/app/views/lecturers/post_created.text.haml
TeacherMailer#post_created

= @greeting + ", find me in app/views/teacher_mailer/post_created.text.haml"

project-master/app/views/lecturers/run_algo.html.haml
= simple_form_for :search, url: lecturer_runAlgo_path do |f|
  = f.label :currentGroupSet, "Select Project:"
  = f.select :currentGroupSet, getGroupSetAlgorithm
 
  = f.button :submit, "Run algorithm", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size:20px'
    

project-master/app/views/lecturers/upload_csv.html.haml
%h1 Upload CSV Files

%br

%p{:style => "font-size: 20px"}  Upload lists of students in this page in the form of CSV files.

%p Choose a csv file from your device and click the "Upload CSV" button.

%br
= simple_form_for :search, url: lecturer_importstudents_path do |f| 
 
   = f.label :file, "Upload CSV File"
   = f.file_field :file, required: true 
   = f.button :submit, "Upload CSV", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Please ensure that a CSV file has been selected before submission. Use the "Browse" button to upload a file.'