project-master/config/routes.rb
Rails.application.routes.draw do

  resources :groupmembers
  resources :course_modules
  resources :projects
  resources :preferences
  resources :pairings
  resources :groups
  resources :lecturers
  resources :students
  devise_for :users
  resources :course_modules
  resources :projects
  resources :preferences
  resources :pairings
  resources :groups
  resources :students
  resources :lecturers do
    collection {post :import}
  end
  resources :admins
  resources :users

  mount EpiCas::Engine, at: "/"
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all
  get "/suspend", to: "users#suspend", :as => 'suspend'
  get '/createPreference' => 'preferences_controller#createPreference', :as => 'createPreference'

  get :ie_warning, to: 'errors#ie_warning'
  get 'lecturer_dashboard', to: 'lecturers#dashboard'
  get 'student_dashboard', to: 'students#dashboard'
  get 'select_groupset', to: 'lecturers#groupsetSelect'
  get 'lecturer_organise', to: 'lecturers#organiseGroups'
  get 'lecturer_organise_teams', to: 'lecturers#organiseTeams'
  get 'lecturer_organise_students', to: 'lecturers#organiseStudents'
  get 'lecturer_grouping', to: 'lecturers#grouping'
  get 'group_details', to: 'lecturers#group_details'
  get 'lecturer_form', to: 'groups#new'
  get 'preferences_form', to: 'preferences#_form'
  get 'profile', to: 'users#profile'
  get 'upload', to: 'lecturers#upload_csv'
  get 'form', to: 'students#form'
  get 'emails', to: 'lecturers#emails'
  get 'lecturers_main_page', to: 'lecturers#index'
  get 'students_main_page', to: 'students#index'
  get 'my_group', to: 'students#mygroup'
  get 'admin_user_info', to: 'admins#user_info'
  get 'run_algo', to: 'lecturers#run_algo'
  post 'lecturer/runAlgo', to: 'lecturers#runAlgo'
  post 'admin/importlecturers' , to: 'admins#import_lecturers'
  post 'lecturer/importstudents' , to: 'lecturers#import_students'
  post 'lecturer/setCurrentGroupSet', to: 'lecturers#setCurrentGroupSet'
  post 'lecturer/setCurrentGroupSetOrganise', to: 'lecturers#setCurrentGroupSetOrganise'
  post 'lecturer/setCurrentGroupSetAssigned', to: 'lecturers#setCurrentGroupSetAssigned'
  post 'lecturer/setCurrentModule', to: 'lecturers#setCurrentModule'
  post 'student/setCurrentModule', to: 'students#setCurrentModule'
  post 'lecturer/setTeam', to: 'lecturers#setTeam'
  post 'lecturer/removeStudent', to: 'lecturers#removeStudent'
  post 'lecturer/addStudent', to: 'lecturers#addStudent'
  post 'admin/suspenduser', to: 'admins#suspend_user'
  post 'admin/promoteadmin', to: 'admins#promote_admin'
  post 'admin/unsuspenduser', to: 'admins#unsuspend_user'
  post 'admin/demoteadmin', to: 'admins#demote_admin'
  post 'student/getgroup', to: 'students#get_group'
  get 'lecturer/exportGroupMembers', to: 'lecturers#exportGroupMembers'

  # admins routes
  get 'admins_main_page', to: 'admins#index'
  get 'admin_csv', to: 'admins#upload_csv'
  get 'user_info', to: 'admins#user_info'
  
  get 'classlistexport', to: 'admins#classlist_csv'

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # Commented out temporarily to be used to test admin pages
  # TO BE REMOVED BEFORE FINAL SUBMISSION
   #root to: "admins#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project-master/app/views/layouts/_svg_logo.html.haml
%svg{:style => "display: none;", :xmlns => "http://www.w3.org/2000/svg"}
  %symbol#bootstrap{:viewbox => "0 0 118 94"}
    %title Bootstrap
    %path{"clip-rule" => "evenodd", :d => "M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z", "fill-rule" => "evenodd"}
  %symbol#home{:viewbox => "0 0 16 16"}
    %path{:d => "M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"}
  %symbol#speedometer2{:viewbox => "0 0 16 16"}
    %path{:d => "M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"}
    %path{:d => "M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z", "fill-rule" => "evenodd"}
  %symbol#table{:viewbox => "0 0 16 16"}
    %path{:d => "M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"}
  %symbol#people-circle{:viewbox => "0 0 16 16"}
    %path{:d => "M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"}
    %path{:d => "M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z", "fill-rule" => "evenodd"}
  %symbol#grid{:viewbox => "0 0 16 16"}
    %path{:d => "M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"}

project-master/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SoftwareHutTeam10 - #{content_for(:title)}
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "content-type"}
    = stylesheet_pack_tag "styles", media: :all
    = javascript_pack_tag "application"
    = favicon_link_tag '/favicon.ico'
    = csrf_meta_tags

  %body.bg-light
    = render 'layouts/svg_logo'

    %header.p-3.mb-3.border-bottom
      .container
        .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
          %a.d-flex.align-items-center.mb-2.mb-lg-0.text-dark.text-decoration-none{:href => "/"}
            %img.bi.me-2{"aria-label" => "Bootstrap", :height => "55", :role => "img", :width => "130", :src => "https://www.k-int.com/wp-content/uploads/2018/01/University-of-Sheffield-logo.jpg"}
            - if user_signed_in?
              - if current_user.lecturer?
                %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
                  %li.fw-bolder.m-2
                    = link_to 'Home', lecturers_main_page_path, title: 'Go to the home page', class: 'nav-link px-2 link-secondary'
              - elsif current_user.admin?
                %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
                  %li.fw-bolder.m-2
                    = link_to 'Home', "admins_main_page", title: 'Go to the home page', class: 'nav-link px-2 link-secondary'
              - else
                %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
                  %li.fw-bolder.m-2
                    = link_to 'Home', students_main_page_path, title: 'Go to the home page', class: 'nav-link px-2 link-secondary'    
          %form.col-12.col-lg-auto.mb-3.mb-lg-0.me-lg-3
          - if user_signed_in?
            %a.nav-link.dropdown-toggle{ href: '#', data: { bs_toggle: :dropdown }, aria: { expanded: false } }
              = current_user.email
            %nav.dropdown-menu.dropdown-menu-lg-end
              = link_to 'Sign out', destroy_user_session_path, class: 'dropdown-item', method: :delete, title: "Log out of the system"


    .flash-messages
      - flash.each do |name, msg|
        - next unless name == 'alert' || name == 'notice'
        .alert.alert-info
          .container
            = msg
            %a{ href: '#', title: 'Hide this message', data: { bs_dismiss: :alert } } Dismiss

    %main
      .container= yield

    %footer.mt-auto.my-5.pt-5.text-muted.text-center.text-small
      %p.mb-1 &copy; Team 10 #{Date.today.year}

project-master/app/views/layouts/plain_error.html.haml
!!!
%html
  %head
    %title SoftwareHutTeam10 - #{content_for(:title)}
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{ :'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    = stylesheet_link_tag    "application", media: :all
    = javascript_include_tag "application"
    = favicon_link_tag '/favicon.ico'

  %body.bg-light
    = render 'layouts/svg_logo'

    %header.p-3.mb-3.border-bottom
      .container
        .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
          %a.d-flex.align-items-center.mb-2.mb-lg-0.text-dark.text-decoration-none{:href => "/"}
            %svg.bi.me-2{"aria-label" => "Bootstrap", :height => "32", :role => "img", :width => "40"}
              %use{"xlink:href" => "#bootstrap"}
          %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
            %li
              = link_to 'Home', root_path, title: 'Go to the home page', class: 'nav-link px-2 link-secondary'
            %li
              %a.nav-link.px-2.link-dark{:href => "#"} Inventory
            %li
              %a.nav-link.px-2.link-dark{:href => "#"} Customers
            %li
              %a.nav-link.px-2.link-dark{:href => "#"} Products
          %form.col-12.col-lg-auto.mb-3.mb-lg-0.me-lg-3
            %input.form-control{"aria-label" => "Search", :placeholder => "Search...", :type => "search"}
          .dropdown.text-end
            %a#dropdownUser1.d-block.link-dark.text-decoration-none.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#"}
              %img.rounded-circle{:alt => "mdo", :height => "32", :src => "https://github.com/epigenesys.png", :width => "32"}
            %ul.dropdown-menu.text-small{"aria-labelledby" => "dropdownUser1", :style => ""}
              %li
                %a.dropdown-item{:href => "#"} New project...
              %li
                %a.dropdown-item{:href => "#"} Settings
              %li
                %a.dropdown-item{:href => "#"} Profile
              %li
                %hr.dropdown-divider/
              %li
                %a.dropdown-item{:href => "#"} Sign out

    = render 'layouts/environment_notice'
    .flash-messages
      - flash.each do |name, msg|
        - next unless name == 'alert' || name == 'notice'
        .alert.fade.in
          .container
            - if name == 'notice'
              = icon('fas', 'check', class: 'flash-success')
            - else
              = icon('fas', 'exclamation-triangle', class: 'flash-error')
            = msg
            %a{ href: '#', title: 'Hide this message', data: { dismiss: :alert } } Dismiss

    .container
      %main
        = yield

    %footer.my-5.pt-5.text-muted.text-center.text-small
      %p.mb-1 &copy; epiGenesys #{Date.today.year}
      %ul.list-inline
        %li.list-inline-item
          = link_to 'epiGenesys', 'https://www.epigenesys.org.uk', target: '_blank', title: 'Go to the epiGenesys website'
        %li.list-inline-item
          %a{:href => "#"} Terms
        %li.list-inline-item
          %a{:href => "#"} Support