project-master/config/routes.rb
Rails.application.routes.draw do

  resources :groupmembers
  resources :course_modules
  resources :projects
  resources :preferences
  resources :pairings
  resources :groups
  resources :lecturers
  resources :students
  devise_for :users
  resources :course_modules
  resources :projects
  resources :preferences
  resources :pairings
  resources :groups
  resources :students
  resources :lecturers do
    collection {post :import}
  end
  resources :admins
  resources :users

  mount EpiCas::Engine, at: "/"
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all
  get "/suspend", to: "users#suspend", :as => 'suspend'
  get '/createPreference' => 'preferences_controller#createPreference', :as => 'createPreference'

  get :ie_warning, to: 'errors#ie_warning'
  get 'lecturer_dashboard', to: 'lecturers#dashboard'
  get 'student_dashboard', to: 'students#dashboard'
  get 'select_groupset', to: 'lecturers#groupsetSelect'
  get 'lecturer_organise', to: 'lecturers#organiseGroups'
  get 'lecturer_organise_teams', to: 'lecturers#organiseTeams'
  get 'lecturer_organise_students', to: 'lecturers#organiseStudents'
  get 'lecturer_grouping', to: 'lecturers#grouping'
  get 'group_details', to: 'lecturers#group_details'
  get 'lecturer_form', to: 'groups#new'
  get 'preferences_form', to: 'preferences#_form'
  get 'profile', to: 'users#profile'
  get 'upload', to: 'lecturers#upload_csv'
  get 'form', to: 'students#form'
  get 'emails', to: 'lecturers#emails'
  get 'lecturers_main_page', to: 'lecturers#index'
  get 'students_main_page', to: 'students#index'
  get 'my_group', to: 'students#mygroup'
  get 'admin_user_info', to: 'admins#user_info'
  get 'run_algo', to: 'lecturers#run_algo'
  post 'lecturer/runAlgo', to: 'lecturers#runAlgo'
  post 'admin/importlecturers' , to: 'admins#import_lecturers'
  post 'lecturer/importstudents' , to: 'lecturers#import_students'
  post 'lecturer/setCurrentGroupSet', to: 'lecturers#setCurrentGroupSet'
  post 'lecturer/setCurrentGroupSetOrganise', to: 'lecturers#setCurrentGroupSetOrganise'
  post 'lecturer/setCurrentGroupSetAssigned', to: 'lecturers#setCurrentGroupSetAssigned'
  post 'lecturer/setCurrentModule', to: 'lecturers#setCurrentModule'
  post 'student/setCurrentModule', to: 'students#setCurrentModule'
  post 'lecturer/setTeam', to: 'lecturers#setTeam'
  post 'lecturer/removeStudent', to: 'lecturers#removeStudent'
  post 'lecturer/addStudent', to: 'lecturers#addStudent'
  post 'admin/suspenduser', to: 'admins#suspend_user'
  post 'admin/promoteadmin', to: 'admins#promote_admin'
  post 'admin/unsuspenduser', to: 'admins#unsuspend_user'
  post 'admin/demoteadmin', to: 'admins#demote_admin'
  post 'student/getgroup', to: 'students#get_group'
  get 'lecturer/exportGroupMembers', to: 'lecturers#exportGroupMembers'

  # admins routes
  get 'admins_main_page', to: 'admins#index'
  get 'admin_csv', to: 'admins#upload_csv'
  get 'user_info', to: 'admins#user_info'
  
  get 'classlistexport', to: 'admins#classlist_csv'

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # Commented out temporarily to be used to test admin pages
  # TO BE REMOVED BEFORE FINAL SUBMISSION
   #root to: "admins#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project-master/app/views/admins/index.html.haml
%h1 Welcome Admin

%br

%p{:style => "font-size: 20px"} Below are the services that are accessible to you.

%button.btn.btn-secondary
 = link_to "Upload CSV Files ", "admin_csv", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Upload lecturer lists in the form of CSV files.'

%button.btn.btn-secondary{:style => "margin: 50px"}
 = link_to "User Information", "user_info", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'View information about all users in the system and manually adjust roles or suspend/unsuspend users.'

%button.btn.btn-secondary
 = link_to "My Profile", "profile", :style=> 'color:black; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'View details of your profile.'

project-master/app/views/admins/upload_csv.html.haml
%h1 Upload CSV Files

%br

%p{:style => "font-size: 20px"}  Upload lists of lecturers in this page in the form of CSV files.

%p{:style => "font-size: 20px"}  Choose a CSV file from your device and click the "Upload CSV" button.

%br

= simple_form_for :search, url: admin_importlecturers_path do |f|    #To be edited
 
   = f.label :file, "Upload CSV File"  
   = f.file_field :file, required: true
   = f.submit "Upload CSV", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Please ensure that a CSV file has been selected before submission. Use the "Choose File" button to upload a file.'

project-master/app/views/admins/user_info.html.haml
%h1 User information

%br

%p{:style => "font-size: 20px"}  The table below displays information about all users in the system.

%table.table.table-bordered.table-secondary{:border => 3, :width=>"60%"}
  %thead
    %tr
      %th Username
      %th Name
      %th Email
      %th Suspended?
      %th Admin

  %tbody
    - User.all.each do |user|
      %tr 
        %td= user.username
        %td= user.givenname
        %td= user.email
        %td= user.suspended 
        %td= user.admin

%br

%p{:style => "font-size: 20px"}  Select user that you wish to suspend.

%br
= simple_form_for :search, url: admin_suspenduser_path do |f|    #To be edited
 
  = f.label :users, "Suspend User"
  = f.select :users, get_users
  = f.submit "Suspend User", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Select the user you wish to suspend from the dropdown box and click this button.'

%br
%br

%p{:style => "font-size: 20px"}  Select user that you wish to unsuspend.

%br
= simple_form_for :search, url: admin_unsuspenduser_path do |f|    #To be edited
 
  = f.label :users, "Unsuspend User"
  = f.select :users, get_users
  = f.submit "Unsuspend User", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Select the user you wish to unsuspend from the dropdown box and click this button.'

%br
%br

%p{:style => "font-size: 20px"}  Select user that you wish to promote to admin.

%br
= simple_form_for :search, url: admin_promoteadmin_path do |f|    #To be edited
 
  = f.label :users, "Promote User"
  = f.select :users, get_users
  = f.submit "Promote User", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Select the user you wish to promote to an admin from the dropdown box and click this button.'

%br
%br

%p{:style => "font-size: 20px"}  Select user that you wish to promote to admin.

%br
= simple_form_for :search, url: admin_demoteadmin_path do |f|    #To be edited
 
  = f.label :users, "Demote User"
  = f.select :users, get_users
  = f.submit "Demote User", :style=> 'color:black; border-width: 0; background-color: #1e90ff; text-decoration:none; padding: 20px; font-size: 20px', :title=> 'Select the user you wish to demote from an admin from the dropdown box and click this button.'

        